server:
  port: 8000

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/capital?useSSL=false&serverTimezone=Asia/Shanghai
    username: capital
    password: capital
    driver-class-name: org.mariadb.jdbc.Driver


logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG